libs =
import libs += libhello%lib{hello}

exe{hello}: {hxx ixx txx cxx}{**} $libs testscript

cxx.poptions =+ "-I$out_root" "-I$src_root"
cxx.poptions =+ "-I$config.hello.import.winrt"
cxx.poptions =+ "-I$config.hello.import.appsdk"
cxx.loptions =+ \
  "/LIBPATH:$config.hello.import.libappsdk"

cxx.loptions =+ "WindowsApp.lib"
cxx.loptions =+ "Microsoft.WindowsAppRuntime.lib"
cxx.loptions =+ "Microsoft.WindowsAppRuntime.Bootstrap.lib"
